<?php

/**
 * Unregister Blocks.
 *
 * @package makerblocks
 */

add_filter('allowed_block_types_all', function ($allowed_blocks, $editor_context): array {
    $allowed_blocks = [
        'core/paragraph',
        'core/heading',
        'core/list',
        'core/list-item',
        'core/quote',
        'core/preformatted',
        'core/pullquote',
        'core/table',
        'core/gallery',
        'core/image',
        'core/video',
        'core/spacer',
        'core/separator',
        'core/shortcode',
        // Additional blocks
        'core/archives',
        'core/audio',
        'core/avatar',
        'core/pattern',
        'core/button',
        'core/buttons',
        'core/calendar',
        'core/categories-list',
        'core/code',
        'core/column',
        'core/columns',
        'core/comment-author-avatar', // deprecated
        'core/comment-author-name',
        'core/comment-content',
        'core/comment-date',
        'core/comment-edit-link',
        'core/comment-reply-link',
        'core/comment-template',
        'core/comments',
        'core/comments-pagination',
        'core/comments-next-page',
        'core/comments-page-numbers',
        'core/comments-previous-page',
        'core/comments-title',
        'core/cover',
        'core/details',
        'core/embed',
        'core/file',
        'core/footnotes',
        'core/form',
        'core/input-field',
        'core/form-submission-notification',
        'core/form-submit-button',
        'core/classic',
        'core/group',
        'core/home-link',
        'core/custom-html',
        'core/latest-comments',
        'core/latest-posts',
        'core/login-out',
        'core/media-text',
        'core/unsupported',
        'core/more',
        'core/navigation',
        'core/custom-link',
        'core/submenu',
        'core/page-break',
        'core/page-list',
        'core/page-list-item',
        'core/pattern-placeholder',
        'core/author',
        'core/author-biography',
        'core/author-name',
        'core/comment', // deprecated
        'core/comments-count',
        'core/comments-form',
        'core/comments-link',
        'core/content',
        'core/date',
        'core/excerpt',
        'core/featured-image',
        'core/post-navigation-link',
        'core/post-template',
        'core/post-terms',
        'core/time-to-read',
        'core/title',
        'core/query-loop',
        'core/no-results',
        'core/pagination',
        'core/next-page',
        'core/page-numbers',
        'core/previous-page',
        'core/query-title',
        'core/rss',
        'core/search',
        'core/site-logo',
        'core/site-tagline',
        'core/site-title',
        'core/social-icon',
        'core/social-icons',
        'core/tag-cloud',
        'core/template-part',
        'core/term-description',
        'core/text-columns', // deprecated
        'core/table-of-contents',
        'core/verse',
    ];

    return $allowed_blocks;
}, 100, 2);

